version: '3.8'

services:
  moneytrackerapp:
    image: moneytracker:latest
    container_name: moneyTrackerApp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://springDB:3306/moneytracker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05102021
    depends_on:
      - springDB
    ports:
      - "8888:8888"
    networks:
      - mysqltest

  springDB:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=05102021
      - MYSQL_DATABASE=moneytracker
    ports:
      - "3307:3306"
    networks:
      - mysqltest
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:

networks:
  mysqltest:
    driver: bridge